#Note 目前的yaml是默认你联网的，若不联网，则需要自己修改模型参数等信息，具体可以看 [这个项目](https://github.com/ciaoyizhen/image_classification) 进行线下配置
name: "chinese-classification"  # task name, used to process title and save dir name
label_config: "configs/label_config.txt"

is_dataset_cached: false
dataset_cache_dir: ""  # datasets module save cache path, if is_dataset_cache is false, it does not take effect

model:
  type: transformers,AutoModelForSequenceClassification
  args:
    pretrained_model_name_or_path: "bert-base-chinese"  # used model

evaluate_metric:
  #! Optional: `evaluate package` could load.  some metric need special process.
  - "accuracy"
  - "recall"
  - "precision"
  - "f1"

processor:
  type: transformers,AutoTokenizer
  args:
    pretrained_model_name_or_path: "bert-base-chinese" # used model

train_args:
  #! Optional: transformers.TrainingArguments
  output_dir: null # if not set, will using outputs/`name`
  eval_strategy: "epoch"
  per_device_train_batch_size: 32
  per_device_eval_batch_size: 64
  save_strategy: "epoch"
  logging_steps: 10
  learning_rate: !!float 5e-5
  num_train_epochs: 2
  logging_first_step: true
  lr_scheduler_type: "cosine"
  weight_decay: !!float 1e-4
  gradient_accumulation_steps: 1
  max_grad_norm: 0.01

train_dataset:  # train_dataset configure
  type:  src.dataset,Dataset # used class name, format `{module_name},{class_name}`
  args:  # class args
    data_paths:
      - data/train/train.txt  # data_path  Currently only .txt format is implemented `{img_path}\t{label}`

validation_dataset:
  type: src.dataset,Dataset
  args:
    data_paths:
      - data/validation/validation.txt

test_dataset:
  type: src.dataset,Dataset
  args:
    data_paths:
      - data/test/test.txt

